version: '3.1'
services:
  typerom-test-db:
    container_name: typeorm-test
    image: mysql:8.0.23
    platform: linux/amd64
    volumes:
      - ./mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=1111
      - MYSQL_PASSWORD=1111
      - MYSQL_DATABASE=typeorm-test
    ports:
      - 9999:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp --sql_mode=IGNORE_SPACE --max_connections=10000 --wait_timeout=60000 --default-authentication-plugin=mysql_native_password
